# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml
    - name: Upload result
      uses: actions/upload-artifact@v1
      with:
        name: webGameLauncher-0.0.1-SNAPSHOT-jar-with-dependencies.${{steps.version.outputs.prop}}.${{ github.run_number }}-${{ github.sha }}.jar
        path: target/webGameLauncher-0.0.1-SNAPSHOT-jar-with-dependencies.jar
        
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        # GitHub secret token
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Git tag (for automatic releases)
        automatic_release_tag: Prototype_${{steps.version.outputs.prop}}.${{ github.run_number }}-${{ github.sha }}
        # Should this release be marked as a pre-release?
        prerelease: True
        # Release title (for automatic releases)
        title: Prototype_${{steps.version.outputs.prop}}.${{ github.run_number }}-${{ github.sha }}
        # Assets to upload to the release
        files: target/webGameLauncher-0.0.1-SNAPSHOT-jar-with-dependencies.jar

  
